server:
  port: 8080

spring:
  application:
    name: weather-service
  datasource:
    name: isfandiyor
    password: isfandiyor_password
    url: jdbc:mysql://localhost:3306/weather-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    drop-first: false
    enabled: false

springdoc:
  swagger-ui:
    enabled: true